---
order: 11
format:
    html:
        toc: false
original: https://christophm.github.io/interpretable-ml-book/future.html
---

<!-- {{< include ../_in_progress.qmd >}} -->
{{< include ../_original.qmd >}}

# 11 - Un regard dans une boule de cristal

Quel est l’avenir de l’apprentissage automatique interprétable ? Ce chapitre est un exercice mental spéculatif et une estimation subjective de la façon dont l’apprentissage automatique interprétable se développera. J'ai ouvert le livre sur [des nouvelles](/02-introduction/02.1-short_stories.qmd) plutôt pessimistes et j'aimerais conclure sur une perspective plus optimiste.

J’ai basé mes « prédictions » sur trois prémisses :

1. **Numérisation : Toute information (intéressante) sera numérisée**.<br>
Pensez à l’argent dématérialisé et aux transactions en ligne. Pensez aux livres électroniques, à la musique et aux vidéos. Pensez à toutes les données sensorielles sur notre environnement, notre comportement humain, les processus de production industrielle, etc. Les moteurs de la numérisation de tout sont les suivants : ordinateurs/capteurs/stockage bon marché, effets d'échelle (le gagnant remporte tout), nouveaux modèles commerciaux, chaînes de valeur modulaires, pression sur les coûts et bien plus encore.

1. **Automatisation : lorsqu'une tâche peut être automatisée et que le coût de l'automatisation est inférieur au coût d'exécution de la tâche au fil du temps, la tâche sera automatisée**.<br>
Même avant l’introduction de l’ordinateur, nous avions un certain degré d’automatisation. Par exemple, la machine à tisser a automatisé le tissage ou la machine à vapeur a automatisé la puissance de travail. Mais les ordinateurs et la numérisation font passer l’automatisation à un niveau supérieur. Le simple fait que vous puissiez programmer des boucles `for`, écrire des macros Excel, automatiser les réponses aux e-mails, etc., montre à quel point un individu peut automatiser. Les guichets de billets automatisent l'achat des billets de train (plus besoin de caissier), les machines à laver automatisent la lessive, les ordres permanents automatisent les transactions de paiement, etc. L'automatisation des tâches libère du temps et de l'argent, il existe donc une énorme incitation économique et personnelle à automatiser les choses. Nous observons actuellement l’automatisation de la traduction linguistique, de la conduite automobile et, dans une moindre mesure, même de la découverte scientifique.

1. **Mauvaise spécification : nous ne sommes pas en mesure de spécifier parfaitement un objectif avec toutes ses contraintes**.<br>
Pensez au génie dans une bouteille qui prend toujours vos souhaits au pied de la lettre : <br>
« Je veux être la personne la plus riche du monde ! » -> Vous devenez la personne la plus riche, mais comme effet secondaire, la monnaie que vous détenez s'effondre à cause de l'inflation.<br>
« Je veux être heureux pour le reste de ma vie ! » -> Les 5 minutes suivantes vous vous sentez très heureux, puis le génie vous tue.<br>
« Je souhaite la paix dans le monde ! » -> Le génie tue tous les humains.<br>
Nous spécifions mal les objectifs, soit parce que nous ne connaissons pas toutes les contraintes, soit parce que nous ne pouvons pas les mesurer. Prenons les entreprises comme exemple de spécification d’objectifs imparfaite. Une société a pour objectif simple de gagner de l’argent pour ses actionnaires. Mais cette spécification ne rend pas compte du véritable objectif, avec toutes ses contraintes, que nous recherchons réellement : par exemple, nous n’apprécions pas qu’une entreprise tue des gens pour gagner de l’argent, empoisonne des rivières ou imprime simplement sa propre monnaie. Nous avons inventé des lois, des réglementations, des sanctions, des procédures de conformité, des syndicats et bien plus encore pour rafistoler la spécification imparfaite des objectifs. Un autre exemple que vous pouvez expérimenter par vous-même est [Paperclips](http://www.decisionproblem.com/paperclips/index2.html), un jeu dans lequel vous jouez à une machine dans le but de produire autant de trombones que possible. AVERTISSEMENT : on en devient accro. Je ne veux pas trop divulgâcher, mais disons que les choses deviennent très vite incontrôlables. En apprentissage automatique, les imperfections dans la spécification des objectifs proviennent d'abstractions de données imparfaites (populations biaisées, erreurs de mesure,…), de fonctions de perte non contraintes, d'un manque de connaissance des contraintes, d'un déplacement de la répartition entre les données de formation et d'application et bien plus encore.

La numérisation entraîne l’automatisation. La spécification imparfaite des objectifs entre en conflit avec l’automatisation. Je prétends que ce conflit sera en partie tempéré par des méthodes d’interprétation.

Le décor de nos pronostics est planté, la boule de cristal est prête, regardons maintenant où pourrait aller le terrain !