project:
  type: website
  render: 
    - "*.qmd"
    - "!source/"
    - "!about.qmd"
    - "!index_default.qmd"
    - "!_in_progress.qmd"
    - "!_original.qmd"

website:
  title: "Apprentissage automatique interprétable"
  sidebar:
    style: "docked"
    search: true
    contents: auto
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2018-2024, Christoph Molnar / Traduction 2024 : Nicolas Guillard"
  
format:
  html:
    metadata:
      licence: CC BY-NC-SA
    css: styles.css
    #date-modified: 06/10/2024
    fig-align: center
    fig-cap-location: bottom
    lang: fr-FR
    link-external-newwindow: true
    number-depth: 4
    theme: flatly
    toc: true
    toc-title: Dans cette page
    toc-depth: 4
    toc-expand: 4