project:
  type: website
  render: 
    - "*.qmd"
    - "02.0-Introduction/*"
    - "!source/*"

website:
  title: "Apprentissage automatique interprétable"
  sidebar:
    style: "docked"
    search: true
    contents: auto
  page-navigation: true
  back-to-top-navigation: true
  
format:
  html:
    lang: fr-FR
    theme: cosmo
    css: styles.css
    date-modified: 01/25/2024
    toc: true
    toc-title: Dans cette page
    number-depth: 4
    toc-depth: 4
    toc-expand: 4
    link-external-newwindow: true
    fig-align: center
    fig-cap-location: bottom