project:
  type: website
  render: 
    - "*.qmd"
    - "!source/"
    - "!about.qmd"
    - "!index_default.qmd"
    - "!_in_progress.qmd"
    - "!_original.qmd"
    - "!*/_references.qmd"
  output-dir: "/Users/me/Dropbox (Compte personnel)/Perso NG/Sciences/_AI/__Portfolio/nicolasguillard.github.io/interpretable-ml-book-fr"

website:
  title: "Apprentissage automatique interprétable"
  sidebar:
    style: "docked"
    search: true
    contents: auto
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2018-2025, Christoph Molnar <br> Traduction 2024-2025 : Nicolas Guillard"
  cookie-consent: false
  
format:
  html:
    metadata:
      licence: CC BY-NC-SA
    css: styles.css
    date-modified: 02/19/2025
    fig-align: center
    fig-cap-location: bottom
    lang: fr-FR
    link-external-newwindow: true
    number-depth: 4
    theme: flatly
    toc: true
    toc-title: Dans cette page
    toc-depth: 4
    toc-expand: 4