---
order: 1
format:
    html:
        toc: false
original: https://christophm.github.io/interpretable-ml-book/preface-by-the-author.html
---

<!-- {{< include ../_in_progress.qmd >}} -->
{{< include ../_original.qmd >}}

# 1 - Préface de l'auteur

Ce livre a commencé comme un projet secondaire lorsque je travaillais comme statisticien dans la recherche clinique. Je travaillais quatre jours par semaine, et pendant mon "jour de congé", je travaillais sur des projets annexes. Finalement, l'apprentissage automatique interprétable est devenu l'un de mes projets annexes. Au début, je n'avais pas l'intention d'écrire un livre. J'étais simplement intéressé à en savoir plus sur l'apprentissage automatique interprétable et je cherchais de bonnes ressources pour apprendre.
Étant donné le succès de l'apprentissage automatique et l'importance de l'interprétabilité, je m'attendais à ce qu'il y ait des tonnes de livres et de tutoriels sur ce sujet. Mais je n'ai trouvé que les articles de recherche pertinents et quelques publications de blogs éparpillés sur Internet, et rien qui n'offre une bonne vue d'ensemble. Pas de livres, pas de tutoriels, pas d'articles de synthèse, rien. Cette lacune m'a inspiré à commencer à écrire ce livre. J'ai fini par écrire le livre que j'aurais souhaité avoir à disposition lorsque j'ai commencé mes études sur l'apprentissage automatique interprétable. Mon intention avec ce livre était double : apprendre pour moi-même et partager ces nouvelles connaissances avec les autres.

<!-- Introduction to Author -->
J'ai obtenu mon baccalauréat et ma maîtrise en statistiques à l'Université Ludwig-Maximilian de Munich, en Allemagne. La plupart de mes connaissances en apprentissage automatique ont été acquises en autodidacte à travers des cours en ligne, des compétitions, des projets annexes et des activités professionnelles. Mon parcours en statistiques a été une excellente base pour me lancer dans l'apprentissage automatique, et surtout dans l'interprétabilité. En statistiques, l'accent est mis sur la création de modèles de régression interprétables. Après avoir terminé ma maîtrise en statistiques, j'ai décidé de ne pas poursuivre un doctorat, car je n'avais pas apprécié la phase de rédaction de mon mémoire de maîtrise. Écrire me stressait tout simplement trop. J'ai donc pris des emplois de scientifique des données dans une start-up de Fintech et de statisticien dans la recherche clinique. Après ces trois années dans l'industrie, j'ai commencé à écrire ce livre et quelques mois plus tard, j'ai commencé un doctorat en apprentissage automatique interprétable. En travaillant sur ce livre, j'ai redécouvert le plaisir d'écrire et cela m'a aidé à développer une passion pour la recherche.

Ce livre couvre de nombreuses techniques d'apprentissage automatique interprétable. Dans les premiers chapitres, j'introduis le concept d'interprétabilité et j'explique pourquoi l'interprétabilité est nécessaire. Il y a même quelques courtes histoires ! Le livre discute des différentes propriétés d'une explication et de ce que les humains considèrent être une bonne explication. Nous discuterons ensuite des modèles d'apprentissage automatique qui sont intrinsèquement interprétables, par exemple les modèles de régression et les arbres de décision. Le principal sujet de ce livre porte sur les méthodes d'interprétabilité agnostiques au modèle. Agnostique au modèle signifie que ces méthodes peuvent être appliquées à n'importe quel modèle d'apprentissage automatique et qu'elles ne sont appliquées qu'après que le modèle ait été entraîné. Cette indépendance vis-à-vis du modèle rend les méthodes agnostiques très flexibles et puissantes. Certaines techniques expliquent comment les prédictions individuelles ont été produites, comme les explications locales interprétables agnostiques au modèle (LIME) et les valeurs de Shapley. D'autres techniques décrivent le comportement moyen du modèle à travers un ensemble de données. Nous apprendrons dans ce livre le graphique de dépendance partielle, les effets locaux accumulés, l'importance des caractéristiques par permutation et de nombreuses autres méthodes. Une catégorie spéciale concerne les méthodes basées sur des exemples qui produisent des points de données comme explications. Les explications contrefactuelles, les prototypes, les instances influentes et les exemples adverses sont des méthodes basées sur des exemples, qui sont discutées dans ce livre. Celui-ci se conclut par quelques réflexions sur ce que pourrait être l'avenir de l'apprentissage automatique interprétable.

Vous n'avez pas à lire le livre du début à la fin, vous pouvez aller et venir et vous concentrer sur les techniques qui vous intéressent le plus. Je recommande seulement que vous commenciez par l'introduction suivi du chapitre sur l'interprétabilité. La plupart des chapitres suivent une structure similaire et se concentrent sur une méthode d'interprétation. Le premier paragraphe résume la méthode.
Ensuite, j'essaie de l'expliquer de manière intuitive sans me fier aux formules mathématiques. Puis nous examinons sa théorie afin d'obtenir une compréhension approfondie de son fonctionnement. Vous ne serez pas épargné durant cette étape, car la théorie contiendra des formules. Je crois qu'une nouvelle méthode est mieux comprise à l'aide d'exemples. Par conséquent, chaque méthode est appliquée à des données réelles. Certaines personnes disent que les statisticiens sont des gens très critiques.
Pour moi, c'est vrai, car chaque chapitre contient des discussions critiques sur les avantages et les inconvénients de la méthode d'interprétation respective. Ce livre n'est pas une publicité pour telle ou telle méthode, mais il devrait vous aider à décider si une méthode fonctionne bien pour votre application ou non. Dans la dernière section de chaque chapitre, des implémentations logicielles disponibles sont décrites.

L'apprentissage automatique a reçu une grande attention de la part de nombreuses personnes dans la recherche et l'industrie. Parfois, l'apprentissage automatique est surestimé dans les médias, mais il existe de nombreuses applications réelles et impactantes. L'apprentissage automatique est une technologie puissante pour les produits, la recherche et l'automatisation. Aujourd'hui, l'apprentissage automatique est utilisé, par exemple, pour détecter des transactions financières frauduleuses, recommander des films et classifier des images.
Il est souvent crucial que les modèles d'apprentissage automatique soient interprétables. L'interprétabilité aide les développeurs dans les phases de débogage et d'amélioration, construit la confiance dans le modèle, justifie les prédictions de ce dernier et mène à de nouvelles connaissances. Le besoin croissant d'interprétabilité de l'apprentissage automatique est une conséquence naturelle d'une utilisation accrue de l'apprentissage automatique.
Ce livre est devenu une ressource précieuse pour de nombreuses personnes. Les instructeurs l'utilisent pour introduire auprès des étudiants les concepts de l'apprentissage automatique interprétable. J'ai reçu des e-mails de plusieurs étudiants de maîtrise et de doctorat qui m'ont dit que ce livre était le point de départ et la référence la plus importante pour leurs thèses. Il a aidé les chercheurs impliqués dans les domaines de l'écologie, de la finance, de la psychologie, etc., qui utilisent l'apprentissage automatique pour comprendre leurs données. Des scientifiques des données de l'industrie m'ont dit qu'ils utilisaient le livre "Apprentissage Machine Interprétable" pour leur travail et le recommandent à leurs collègues. Je suis heureux que de nombreuses personnes en aient bénéficié et soient devenues des experts en interprétation de modèles.

Je recommanderais ce livre aux praticiens qui souhaitent un aperçu des techniques leur permettant de rendre leurs modèles d'apprentissage automatique plus interprétables. Il pourrait être également bénéfique aux étudiants et aux chercheurs (et toute autre personne) qui s'intéressent à ce sujet. Afin de tirer le meilleur parti de ce livre, il est recommandé de disposer d'une compréhension de base de l'apprentissage automatique, et également d'avoir des connaissances en mathématiques de niveau universitaire pour pouvoir interpréter la théorie et les formules présentées dans ce livre. Il devrait être possible, cependant, de comprendre la description intuitive de la méthode au début de chaque chapitre sans les mathématiques.

J'espère que vous apprécierez de livre!