---
format:
    html:
        toc: false
---

{{< include ../_in_progress.qmd >}}

## 2.2 - Qu'est-ce que l'apprentissage automatique ?

L'apprentissage automatique est un ensemble de méthodes que les ordinateurs utilisent pour faire et améliorer des prédictions ou des comportements basés sur des données.

Par exemple, pour prédire la valeur d'une maison, l'ordinateur apprendrait des motifs à partir de ventes de maisons passées. Le livre se concentre sur l'apprentissage automatique supervisé, qui couvre tous les problèmes de prédiction où nous disposons d'un ensemble de données pour lequel nous connaissons déjà le résultat d'intérêt (par exemple, les prix des maisons passées) et souhaitons apprendre à prédire le résultat pour de nouvelles données. Exclus de l'apprentissage supervisé sont, par exemple, les tâches de regroupement (= apprentissage non supervisé) où nous n'avons pas de résultat spécifique d'intérêt, mais voulons trouver des clusters de points de données. Sont également exclus des choses comme l'apprentissage par renforcement, où un agent apprend à optimiser une certaine récompense en agissant dans un environnement (par exemple, un ordinateur jouant à Tetris). Le but de l'apprentissage supervisé est d'apprendre un modèle prédictif qui relie les caractéristiques des données (par exemple, taille de la maison, emplacement, type de sol, ...) à une sortie (par exemple, prix de la maison). Si la sortie est catégorique, la tâche est appelée classification, et si elle est numérique, elle est appelée régression. L'algorithme d'apprentissage automatique apprend un modèle en estimant des paramètres (comme des poids) ou en apprenant des structures (comme des arbres). L'algorithme est guidé par une fonction de score ou de perte qui est minimisée. Dans l'exemple de la valeur de la maison, l'algorithme minimise la différence entre le prix estimé de la maison et le prix prédit. Un modèle d'apprentissage automatique entièrement formé peut alors être utilisé pour faire des prédictions pour de nouvelles instances.

L'estimation des prix des maisons, les recommandations de produits, la détection des panneaux de signalisation, la prédiction de défaut de crédit et la détection de fraude : tous ces exemples ont en commun qu'ils peuvent être résolus par l'apprentissage automatique. Les tâches sont différentes, mais l'approche est la même :

- Étape 1 : Collecte de données. Plus il y en a, mieux c'est. Les données doivent contenir le résultat que vous souhaitez prédire et des informations supplémentaires à partir desquelles effectuer la prédiction. Pour un détecteur de panneaux de signalisation ("Y a-t-il un panneau de signalisation dans l'image ?"), vous collecteriez des images de rues et indiqueriez si un panneau de signalisation est visible ou non. Pour un prédicteur de défaut de crédit, vous avez besoin de données passées sur des prêts réels, d'informations sur le fait que les clients étaient en défaut de paiement avec leurs prêts, et de données qui vous aideront à faire des prédictions, telles que le revenu, les défauts de crédit passés, et ainsi de suite. Pour un programme automatique d'estimation de la valeur des maisons, vous pourriez collecter des données de ventes de maisons passées et des informations sur l'immobilier telles que la taille, l'emplacement, etc.
- Étape 2 : Entrez ces informations dans un algorithme d'apprentissage automatique qui génère un modèle de détecteur de panneaux, un modèle de notation de crédit ou un estimateur de valeur de maison.
- Étape 3 : Utilisez le modèle avec de nouvelles données. Intégrez le modèle dans un produit ou un processus, tel qu'une voiture autonome, un processus de demande de crédit ou un site Web de marché immobilier.

Les machines surpassent les humains dans de nombreuses tâches, comme jouer aux échecs (ou plus récemment au Go) ou prédire la météo. Même si la machine est aussi bonne qu'un humain ou un peu moins bonne dans une tâche, il reste de grands avantages en termes de vitesse, de reproductibilité et d'échelle. Un modèle d'apprentissage automatique une fois mis en œuvre peut accomplir une tâche beaucoup plus rapidement que les humains, fournit de manière fiable des résultats cohérents et peut être copié à l'infini. Répliquer un modèle d'apprentissage automatique sur une autre machine est rapide et bon marché. La formation d'un humain pour une tâche peut prendre des décennies (surtout lorsqu'ils sont jeunes) et est très coûteuse.

Un inconvénient majeur de l'utilisation de l'apprentissage automatique est que les informations sur les données et la tâche que la machine résout sont cachées dans des modèles de plus en plus complexes. Vous avez besoin de millions de nombres pour décrire un réseau neuronal profond, et il n'y a aucun moyen de comprendre le modèle dans son intégralité. D'autres modèles, comme la forêt aléatoire, se composent de centaines d'arbres de décision qui "votent" pour les prédictions. Pour comprendre comment la décision a été prise, vous devriez regarder dans les votes et les structures de chacun des centaines d'arbres. Cela ne fonctionne tout simplement pas, peu importe votre intelligence ou la qualité de votre mémoire de travail. Les modèles les plus performants sont souvent des mélanges de plusieurs modèles (également appelés ensembles) qui ne peuvent pas être interprétés, même si chaque modèle individuel pourrait l'être. Si vous vous concentrez uniquement sur la performance, vous obtiendrez automatiquement des modèles de plus en plus opaques. Les modèles gagnants dans les compétitions d'apprentissage automatique sont souvent des ensembles de modèles ou des modèles très complexes tels que les arbres boostés ou les réseaux neuronaux profonds.
